### PR TITLE
Styling fix - add clearfix

### PR DESCRIPTION
**Pull request by yacon**
otherwise the line breaks are not displayed correctly

### CODE REVIEW

**Comment by nsams** [comment]
+1, but 3.8?

**Comment by yacon** [comment]
In my opinion it is a bug fix...
Question is: will it destroy the layout of existing webs.
In that case I would say master.

**Comment by nsams** [comment]
My vote goes for 3.9, but @mariokemetinger should decide

**Comment by mariokemetinger** [comment]
There is no problem to add it in 3.8. I looked at several webs and nothing changes with clearfix or the clearfix is already added. In my opinion it's a bug fix too. Go for it!

**Comment by yacon** [comment]
merged to 3.9 xD

**Pull request closed without merging**
