### PR TITLE
Allow kwfSessionToken as header Param

### PR DESCRIPTION
**Pull request by yacon**
This is useful for frontend developement with apis
e.g. jquery: use the setRequestHeader method in $.ajaxSend

### CODE REVIEW

**Comment by nsams** [comment]
- please rebase to current 3.8
- also implement in Kwf/Controller/Action.php

**Comment by nsams** [comment]
*ping* :D

**Comment by yacon** [comment]
rebased ... wth

**Comment by yacon** [comment]
aaand also implemented in Kwf_Controller_Action

**Comment by yacon** [comment]
will be added in 3.9

**Pull request closed without merging**
