### PR TITLE
Use html5 elements

### PR DESCRIPTION
**Pull request by nsams**

### CODE REVIEW

**Comment by fraxachun** [comment]
Kwc_Articles_Directory_View_Component should use article tags

**Comment by fraxachun** [comment]
:+1:

**Comment by fraxachun** [comment]
:+1:

**Comment by yacon** [comment]
:+1:

**Comment by nsams** [comment]
merged with ecda7fb7419321a95a9a1881cd00a3a68b61dc46 into 4.1

**Pull request closed without merging**
